// Generated by CoffeeScript 1.6.2
exports.fetch = function(model) {
  var https, options, sites, x, _i, _len, _results;

  https = require('https');
  sites = ["1713053037", "2099651830", "1765460742", "2185753250", "1742829237", "3211932302", "2811066792", "2368119691", "1341267693", "1273034312", "2172256513", "2181434512", "1765460742", "2129620715", "2808921022", "1610362247", "1624763627", "1644225642", "1573047053", "1495037557", "1919131861", "1222135407", "1653460650", "1191965271", "2109300743", "1891422510", "1918182630", "2195315124", "1640516504", "1920061532", "1893786465", "2093879035", "2377059260", "1947267610", "1848155523", "2720880354", "2141100877", "1708242827", "2267520473", "2272568451", "1454064140", "1733950851", "2124580897", "2170470811"];
  _results = [];
  for (_i = 0, _len = sites.length; _i < _len; _i++) {
    x = sites[_i];
    options = {
      host   : 'api.weibo.com',
      port   : 443,
      path   : '/2/statuses/user_timeline.json?source=2879718887&uid=' + x + '&feature=1&count=1',
      method : 'get'
    };
    _results.push(https.request(options, function(res) {
      var result;

      result = '';
      return res.on('data', function(data) {
        return result += data;
      }).on('end', function() {
        var i, itemOne, tweets, _j, _len1, _results1;

        tweets = JSON.parse(result);
        tweets = tweets.statuses;
        if (tweets && tweets.length) {
          _results1 = [];
          for (_j = 0, _len1 = tweets.length; _j < _len1; _j++) {
            i = tweets[_j];
            if (i.text.match(/预订|粉丝|微博|屏蔽|有奖|奖品|大奖|转发|转让|微信/) || i.bmiddle_pic === void 0) {

            } else {
              itemOne            = new model();
              itemOne.text       = i.text;
              itemOne.image_url  = i.bmiddle_pic;
              itemOne.author     = i.user.name;
              itemOne.created_at = i.created_at;
              itemOne.weibo_id   = i.mid;
              itemOne.source     = "weibo";
              itemOne.site_id    = i.user.id;
              itemOne.save(function(err) {
                return console.log(err);
              });
              console.log("\n图片: " + i.bmiddle_pic);
              console.log("内容：" + i.text);
              _results1.push(console.log("by " + i.user.name));
            }
          }
          return _results1;
        }
      });
    }).end());
  }
  return _results;
};
