// Generated by CoffeeScript 1.6.2
exports.translate = function(text, from, to, callback) {
  var MsTranslator, client, params;

  MsTranslator = require('mstranslator');
  client = new MsTranslator({
    client_id: "copyto",
    client_secret: "K4dStcXIggu5j/pp+WZ296iFrxZq6+m/BDWTssNIQNs"
  });
  params = {
    text: text,
    from: from,
    to: to
  };
  return client.initialize_token(function(keys) {
    console.log(keys.access_token);
    return client.translate(params, function(err, data) {
      console.log(data);
      return callback(err, data);
    });
  });
};
